### ISSUE TITLE
Message with {} and SelfLog enabled - fails

### ISSUE THREAD

**Issue by nklv** [SeppPenner/Serilog.Sinks.Telegram#10]
```cs
Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
Log.Warning("whatever contains {}");
```
Causes
```
2021-08-14T07:08:58.4219250Z Exception while emitting periodic batch from Serilog.Sinks.Telegram.TelegramSink: System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   at Serilog.Debugging.SelfLog.WriteLine(String format, Object arg0, Object arg1, Object arg2)
   at Serilog.Sinks.Telegram.TelegramSink.SendMessage(String token, String chatId, String message)
   at Serilog.Sinks.Telegram.TelegramSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

```

**Comment by SeppPenner** [comment]
The stack trace points to TelegramSink.cs:line 229:

https://github.com/SeppPenner/Serilog.Sinks.Telegram/blob/f94dbaec470c95f77b87ffa80508924cd395db66/src/Serilog.Sinks.Telegram/Sinks/Telegram/TelegramSink.cs#L229

I honestly have no idea why this would fail except the fact that `{}` looks like a Serilog structured data formatter (See https://github.com/serilog/serilog/wiki/Structured-Data), but is none...

EDIT: I debugged the code, the error occurs there. The only workaround I can think of by now is to write to Selflog and throw a new message with an error if this formatting issue occurres (Which would have the effect that Selflog throws an error but the message will be sent to Telegram at least):

```csharp
/// <summary>
/// Tries to write to Selflog and throws an exception if a formatting error occurred.
/// </summary>
/// <param name="messageTemplate">The message template</param>
private void TryWriteToSelflog(string messageTemplate)
{
    try
    {
        SelfLog.WriteLine(messageTemplate);
    }
    catch (Exception ex)
    {
        SelfLog.WriteLine($"{ex.Message} {ex.StackTrace}");
        this.options.FailureCallback?.Invoke(ex);
    }
}
```

**Comment by SeppPenner** [comment]
Version https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.Telegram/1.0.15 of the package with the workaround is now online :) Just re-open the issue if it's not working for you or if some related issues occur.
